# Generated by Django 4.2.3 on 2023-07-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('manager', 'manager'), ('staff', 'staff'), ('customer', 'customer')], default='customer', max_length=10),
        ),
    ]
