# Generated by Django 4.2.3 on 2023-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('manager', 'manager'), ('customer', 'customer'), ('staff', 'staff')], max_length=10),
        ),
    ]
