# Generated by Django 4.2.3 on 2023-07-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('staff', 'staff'), ('manager', 'manager'), ('customer', 'customer')], default='customer', max_length=10),
        ),
    ]
